name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - openjdk=11
  - pip
  - pytorch-cuda=12.1
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - pyspark==3.5.1
    - spacy==3.7.5
    - lightning>=2.2.0
    - numpy<2.0.0
    - pandas>=2.2.0
    - matplotlib
    - seaborn
    - scikit-learn
    - pydantic>=2.7.0
    - jupyterlab
    - ipykernel
    - tqdm
    - python-dotenv